version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: ${DB_DATABASE}
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: 'always'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
    volumes:
      - ./tabelas.sql:/docker-entrypoint-initdb.d/tabelas.sql

volumes:
  db_data: